library(utils)
library(gridExtra)
data <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM")
dsUK <- subset(data, geoId=="UK", select=c(dateRep, cases, Cumulative_number_for_14_days_of_COVID.19_cases_per_100000))
dsLT <- subset(data, geoId=="LT", select=c(dateRep, cases, Cumulative_number_for_14_days_of_COVID.19_cases_per_100000))
colnames(dsUK) <- c("date","cases_UK","index14_UK")
colnames(dsLT) <- c("date","cases_LT","index14_LT")
dsAll <- merge(dsUK, dsLT, by.x="date", all.x=TRUE)
dsAll <- within(dsAll, dates <- strftime(strptime(date,"%d/%m/%Y"),"%Y-%m-%d"))
ds0 <- tail(dsAll[ order(dsAll$dates), ], 20)
ds1 <- ds0[, c(6, 2, 3, 4, 5)]
png('covid_uk_lt.png', width=60, height=30, units="cm", res=100)
par(las=2)
par(mfrow=c(1,2))
plot(factor(ds1$dates), ds1$index14_UK, main="UK", xlab="", ylab="", type="p", col="blue")
plot(factor(ds1$dates), ds1$index14_LT, main="LT", xlab="", ylab="", type="p", col="red")
pdf("covid_uk_lt.pdf", height=11, width=10)
grid.table(ds1, rows=NULL)
dev.off()
